### ISSUE TITLE
some issues with interactions and splines

### ISSUE THREAD

**Issue by georgheinze** [georgheinze/logistf#36]
![image](https://user-images.githubusercontent.com/56126472/106753219-aef74680-662b-11eb-90eb-ecc097e8c4dc.png)

**Comment by ljiricka** [comment]
I've corrected all errors except the backward bug. The main problem was that flac couln't deal with interactions, splines were no problem. But now data has to be passed as an argument to flac(). Maybe I can find a better solution for that. 
The call of backward is giving an error because it reorders the terms in the interaction (ns(agec, ...):oc to oc:ns(...) in update.formula) and thus the terms cannot be matched anymore. I'll work on this in the next days

**Comment by georgheinze** [comment]
cool. I don't think it is much of an issue if data has to be passed as argument to flac(). It is the same in other packages, as it has become a new policy in R not to include input data into the output object of a (regression) function.
